export const stats = [
    {
        title: "Total Balance",
        value: "$0.00",
        changeLabel: "+2.5% from last month",
        changeVariant: "success",
        changeIcon: ArrowUpRight,
        icon: PiggyBank,
        accent: "bg-indigo-50 text-indigo-700",
        progress: 62,
        progressColor: "bg-indigo-500",
    },
    {
        title: "Monthly Income",
        value: "$0.00",
        changeLabel: "On track",
        changeVariant: "default",
        changeIcon: ArrowUpRight,
        icon: TrendingUp,
        accent: "bg-green-50 text-green-700",
        progress: 82,
        progressColor: "bg-green-500",
    },
    {
        title: "Monthly Expenses",
        value: "$0.00",
        changeLabel: "-$0 vs budget",
        changeVariant: "destructive",
        changeIcon: ArrowDownRight,
        icon: Wallet,
        accent: "bg-rose-50 text-rose-700",
        progress: 46,
        progressColor: "bg-rose-500",
    },
];